nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
    logging:
        driver: json-file
    restart: always

node1:
    restart: always
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        -  volumeteste:/tmp/volumeteste
    logging:
        driver: json-file
     restart: always
node2:
    restart: always
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        -  volumeteste:/tmp/volumeteste
    logging:
        driver: json-file
     restart: always
node3:
    restart: always
    build: ./node
    links:
        - redis
    ports:
        - "8080"
    volumes:
        -  volumeteste:/tmp/volumeteste
    logging:
        driver: json-file
     restart: always
redis:
    restart: always
    image: redis
    ports:
        - "6379"
    logging:
        driver: json-file
     restart: always