	# Imagem baseada em Ubuntu
FROM    ubuntu

	# Autor/Mantenedor
MAINTAINER Jonathan Baraldi

	# Instalar Node.js e outras dependências
RUN apt-get update && \
	apt-get -y install sudo && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup | sudo -E bash - && \
    apt-get install -y nodejs && \
    apt-get -y install python build-essential nodejs

	# Instalar nodemon
RUN npm install -g nodemon

	# Prover camada de cache para módulos do node
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /src && cp -a /tmp/node_modules /src/

	# Definir diretório de trabalho
WORKDIR /src
ADD . /src

	# Expor porta 8080
EXPOSE  8080

	# Rodar app usando nodemon
CMD ["nodemon", "/src/index.js"]